FROM node:8.9.4-alpine

# for dev only - extend watchers limit for CRA file watchers and auto-reload
COPY ./etc/sysctl.conf /etc/sysctl.conf

# define paths
WORKDIR /app
COPY . /app

EXPOSE 3000

CMD yarn && yarn start
