version: '3'
services:
  db:
    image: postgres:9.6.5-alpine
    restart: always
    ports: ["5432:5432"]
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker}
  redis:
    image: redis:3.2.6-alpine
    restart: always
    ports: ["6379:6379"]
  api:
    environment:
      - NODE_ENV=development
    build: ./api
    depends_on:
      - db
      - redis
    ports: ["3001:3001"]
    volumes:
      - ./api:/app:delegated
  client:
    environment:
      - NODE_ENV=development
    build: ./client
    depends_on:
      - api
    ports: ["3000:3000"]
    volumes:
      - ./client:/app:delegated

# override environment using a production.yml as detailed in https://docs.docker.com/compose/production/