AWSTemplateFormatVersion: '2010-09-09'
Description: "Top Level Stack for test environment resources"

Parameters:
  Environment:
    Type: String
    Description: The environment
    Default: test
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route 53 Zone ID
    Default: Z1ANI7AY159U5Q
  S3TemplateBucket:
    Type: String
    Description: The S3 bucket name where CFN templates are
    Default: forgingadventures-resources
  SslCertificateArn:
    Type: String
    Description: SSL certificate ARN
    Default: arn:aws:acm:us-east-1:466853810010:certificate/f396d6a8-2943-45cf-b232-e84a33b88b6f
  RdsUsername:
    Type: String
    Description: The database admin account username
    Default: postgres
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters
  RdsPassword:
    NoEcho: true
    Type: String
    Description: The database admin account password
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3TemplateBucket}/cfn-templates/vpc.yml"
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: forgingadventures

  Security:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3TemplateBucket}/cfn-templates/security.yml"
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPC.Outputs.VpcId
        VpcCidrBlock: !GetAtt VPC.Outputs.VpcCidrBlock
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: forgingadventures

  Apps:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3TemplateBucket}/cfn-templates/apps.yml"
      Parameters:
        Environment: !Ref Environment
        SslCertificateArn: !Ref SslCertificateArn
        VpcId: !GetAtt VPC.Outputs.VpcId
        VpcSubnetList: !Join [ ",", [ !GetAtt VPC.Outputs.PublicSubnet1, !GetAtt VPC.Outputs.PublicSubnet2] ]
        VpcSecurityGroupList: !Join [ ",", [ !GetAtt Security.Outputs.ElbSecurityGroupId] ]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: forgingadventures

  AppHostname:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt Apps.Outputs.ElbDns
        EvaluateTargetHealth: false
        HostedZoneId: Z35SXDOTRQ7X7K
      HostedZoneName: forgingadventures.com.
      Name: playquest.forgingadventures.com.
      Type: A

  Rds:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3TemplateBucket}/cfn-templates/rds.yml"
      Parameters:
        Environment: !Ref Environment
        HostedZoneId: !Ref HostedZoneId
        VpcSubnetList: !Join [ ",", [ !GetAtt VPC.Outputs.PublicSubnet1, !GetAtt VPC.Outputs.PublicSubnet2 ] ]
        VpcSecurityGroupList: !Join [ ",", [ !GetAtt Security.Outputs.RdsSecurityGroupId, !GetAtt Security.Outputs.DevelopersSecurityGroupId ] ]
        Username: !Ref RdsUsername
        Password: !Ref RdsPassword
        StorageType: standard
        AllocatedStorage: 5
        PubliclyAccessible: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: forgingadventures

  Cache:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3TemplateBucket}/cfn-templates/redis.yml"
      Parameters:
        Environment: !Ref Environment
        HostedZoneId: !Ref HostedZoneId
        VpcSubnetList: !Join [ ",", [ !GetAtt VPC.Outputs.PublicSubnet1, !GetAtt VPC.Outputs.PublicSubnet2 ] ]
        VpcSecurityGroupList: !Join [ ",", [ !GetAtt Security.Outputs.RedisSecurityGroupId, !GetAtt Security.Outputs.DevelopersSecurityGroupId ] ]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: forgingadventures

Outputs:
  ClusterName:
    Description: The ECS Cluster Name
    Value: !GetAtt Apps.Outputs.ClusterName
  PublicSubnet1:
    Description: Public Subnet 1
    Value: !GetAtt VPC.Outputs.PublicSubnet1
  PublicSubnet2:
    Description: Public Subnet 2
    Value: !GetAtt VPC.Outputs.PublicSubnet2
  AppHostname:
    Description: DNS of App Load Balancer
    Value: !Ref AppHostname
